CFLAGS=-Wall -g

all: p1 p2 p3 reverse sum p6 p7 p8 p9 p10 p11 p12 p13 p14 p15 p16 p17 p18

clean:
	rm -f p1
	rm -f p2
	rm -f p3
	rm -f reverse
	rm -f sum
	rm -f p6
	rm -f p7
	rm -f p8
	rm -f p9
	rm -f p10
	rm -f p11
	rm -f p12
	rm -f p13
	rm -f p14
	rm -f p15
	rm -f p16
	rm -f p17
	rm -f p18
